language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    
before_install:
  - wget http://dl.google.com/android/repository/android-ndk-r11-linux-x86_64.zip
  - unzip android-ndk-r11-linux-x86_64
  - export $NDK_HOME='pwd'/android-ndk-r11-linux-x86_64
  

install:
  - chmod +x gradlew
  - git submodule update --init
  - gradlew app:copyNotice
  - gradlew daogenerator:executeDaoGenerator 
  - gradlew app:assembleDebug
